spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT1H
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true


offer:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

infrastructure:
  offer:
    scheduler:
      request:
        delay: PT3H

application:
  security:
    jwt:
      secret-key: secret_key
      expiration: 259200000


scheduler:
  enabled: true
